# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields
import sorl_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('pdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Активное')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='blogs', verbose_name='изображение')),
                ('img_crop_thumbnail', sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='310x280', verbose_name='Обрезка миниатюры')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('pdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Активное')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='gallery', verbose_name='изображение галереи')),
                ('img_crop', sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='1200x600', verbose_name='Обрезка фотографии')),
                ('img_crop_thumbnail', sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='206x140', verbose_name='Обрезка миниатюры')),
                ('text', models.TextField(blank=True, verbose_name='Ифнормация')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('prior', models.IntegerField(default=0, verbose_name='приоритет порядка отображения')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('pdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Активное')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='slider_images', verbose_name='изображение слайдера')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('img_crop', sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='800x300', verbose_name='Обрезка изображения')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
