# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 22:07
from __future__ import unicode_literals

from django.db import migrations
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img_crop',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='1200x600', verbose_name='Обрезка оригинала'),
        ),
    ]
