# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='cropping',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='800x300'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to='slider_images', verbose_name='изображение слайдера'),
        ),
    ]
