# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:57
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170610_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=sorl.thumbnail.fields.ImageField(upload_to='slider_images', verbose_name='изображение слайдера'),
        ),
    ]
