# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20170610_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section11', models.TextField(verbose_name='Блок Обо мне')),
                ('section21', models.TextField(verbose_name='блок 1 тренинги')),
                ('section22', models.TextField(verbose_name='блок 2 тренинги')),
                ('section23', models.TextField(verbose_name='блок 3 тренинги')),
                ('aforizm', models.TextField(verbose_name='Блок Афоризма')),
            ],
        ),
    ]
