# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='info',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='info',
            name='versionname',
            field=models.CharField(default='версия 1', max_length=50, unique=True),
        ),
    ]
