# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:01
from __future__ import unicode_literals

from django.db import migrations
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20170610_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AddField(
            model_name='slider',
            name='img_crop',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='800x300', verbose_name='Обрезка изображения'),
        ),
    ]
