# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='text',
            field=models.TextField(blank=True, verbose_name='Ифнормация'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
