# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:31
from __future__ import unicode_literals

from django.db import migrations
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_auto_20170613_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='img_crop_thumbnail',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='206x140', verbose_name='Обрезка миниатюры'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_crop',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='1200x600', verbose_name='Обрезка фотографии'),
        ),
    ]
